import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "PlayPal",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function BottomNav() {
  return (
    <div className="fixed bottom-0 flex h-16 w-full bg-amber-200 font-bold">
      <div className="flex w-1/2 items-center justify-center">
        <Link href="/profile">Profile</Link>
      </div>
      <div className="flex w-1/2 items-center justify-center">
        <Link href="/">Home</Link>
      </div>
    </div>
  );
}

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex flex-col overflow-x-hidden">
        <main className="flex min-h-screen w-screen flex-col gap-4 p-4 pb-20 md:px-[20%]">
          {children}
        </main>
        <BottomNav />
      </body>
    </html>
  );
}
